version: "3.3"

services:
    notebook:
        build: container
        volumes:
            - ".:/home/jovyan/work"
        environment:
            - "JUPYTER_ENABLE_LAB=yes"
            - "NB_UID=${UID:-1000}"
            - "NB_GID=${GID:-1000}"
        ports:
            - "10000:8888"
